### ISSUE TITLE
Error in DDC variable

### ISSUE THREAD

**Issue by Daniel-Tomas** [out386/ddcbr#2]
I have recently installed ddcutil and when I use your script by default the following error message was given:
`./ddcbr.sh: line 17: ddcutil --nodetect --noverify --bus: command not found`

So I saw the man page of ddcutil and the --nodetect option was missing. I think you are using an older version.
Finally, I removed that flag and it works.

**Comment by out386** [comment]
Thanks - haven't checked in a long time. Will fix.
